### ISSUE TITLE
错误上报过滤掉部分无意义报错

### ISSUE THREAD

**Issue by xxtg666** [This-is-XiaoDeng/XDbot2#120]
### 描述

su群里一大堆报错真正有几条是有用的
建议把这种 `nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_msg timeout')` 之类的报错不上报，在发送报错的时候做一下检查

**Comment by This-is-XiaoDeng** [comment]
其实已经有一定过滤了（指`FinishedException`）
