### ISSUE TITLE
建议添加使用at查询其他用户jrrp

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [This-is-XiaoDeng/XDbot2#28]
### 描述

在`/jrrp <QQ>`指令中，添加使用at查询其他用户人品

如`/jrrp 1744793737`等价于`/jrrp @这里是小邓QwQ`

### 原因

可以方便官版QQ用户，不再需要切换一堆页面查询他人QQ号

**Comment by xxtg666** [comment]
6

**Comment by xxtg666** [comment]
6，那你去写啊（

**Comment by This-is-XiaoDeng** [comment]
6
