### ISSUE TITLE
为/cave增加批量查询 & 批量/use

### ISSUE THREAD

**Issue by chun-awa** [This-is-XiaoDeng/XDbot2#40]
### 描述

如题，命令用法：
- `/cave-q <开始的回声洞ID> <结束的回声洞ID>`
- `/use <物品ID> [次数]`

**Comment by This-is-XiaoDeng** [comment]
彳亍现在批量use已完成

**Comment by This-is-XiaoDeng** [comment]
cave-q给个全名.jpg，类似cave-a=cave add

**Comment by This-is-XiaoDeng** [comment]
已完成，等待上线并测试
