### ISSUE TITLE
更改汇率计算

### ISSUE THREAD

**Issue by YifanZhuZhu** [This-is-XiaoDeng/XDbot2#96]
### 描述

我一个人把他搞通货膨胀了（

### 重现步骤

购买超级多20面骰

### 截图

![NDUGOMO4BJ7L6`8FY~AZWA2](https://user-images.githubusercontent.com/108780374/227707190-5c3427af-d73c-45f2-b141-2a1bed508f9b.png)

**Comment by This-is-XiaoDeng** [comment]
截图呢？

**Comment by YifanZhuZhu** [comment]
截了，你没看到吗？

**Comment by YifanZhuZhu** [comment]
就余额那张图片

**Comment by This-is-XiaoDeng** [comment]
建议重修语文

**Comment by This-is-XiaoDeng** [comment]
我谢谢你

**Comment by YifanZhuZhu** [comment]
？？？
