### ISSUE TITLE
重提：更改汇率计算

### ISSUE THREAD

**Issue by YifanZhuZhu** [This-is-XiaoDeng/XDbot2#97]
### 描述

我一个人干的：

### 重现步骤

大量购买二十面骰，使vi大降价

### 截图

![image](https://user-images.githubusercontent.com/108780374/227707389-ae6e7201-b413-4314-8263-f42cd0007685.png)

**Comment by This-is-XiaoDeng** [comment]
我真的，我就出去一会

**Comment by This-is-XiaoDeng** [comment]
我刚出小区你给我来这么一刀

**Comment by This-is-XiaoDeng** [comment]
我谢谢你

**Comment by This-is-XiaoDeng** [comment]
现在应该没问题了，先close了有问题记得再发
